<a href="https://colab.research.google.com/github/ThunchanokChai/DPDM2023/blob/main/Data102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#loading the data
- directly upload
- mounting Gdrive

# directly upload (temporary)

In [1]:
import pandas

In [3]:
table1 = pandas.read_csv('/content/csv')

In [4]:
table1

,Month_,Year_,Amount_Government,Amount_Sickleave,Amount_Day_Sickleave,Amount_ Personalleave,Amount_ Day_Personalleave,Amount_ Vacationleave,Amount_ Day_Vacationleave
0,ตุลาคม,2565,95,18,28,1,2.0,35,57.0
1,พฤศจิกายน,2565,95,20,57,0,0.0,31,47.0
2,ธันวาคม,2565,94,18,27,3,4.5,47,69.5
3,มกราคม,2566,94,18,27,3,4.5,47,69.5
4,กุมภาพันธ์,2566,100,20,30,2,5.0,32,60.0
5,มีนาคม,2566,100,22,33,2,4.0,47,75.0
6,เมษายน,2566,100,17,29,1,1.0,32,62.0
7,พฤษภาคม,2566,101,26,47,1,2.0,40,74.0
8,มิถุนายน,2566,101,25,39,2,3.0,34,61.0

In [6]:
table1.shape

(9, 9)

#mounting with Gdrive

In [9]:
#mounting colab with Google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
table_from_drive = pandas.read_csv('/content/drive/MyDrive/DPDM23_DATA/csv')

In [11]:
table_from_drive

,Month_,Year_,Amount_Government,Amount_Sickleave,Amount_Day_Sickleave,Amount_ Personalleave,Amount_ Day_Personalleave,Amount_ Vacationleave,Amount_ Day_Vacationleave
0,ตุลาคม,2565,95,18,28,1,2.0,35,57.0
1,พฤศจิกายน,2565,95,20,57,0,0.0,31,47.0
2,ธันวาคม,2565,94,18,27,3,4.5,47,69.5
3,มกราคม,2566,94,18,27,3,4.5,47,69.5
4,กุมภาพันธ์,2566,100,20,30,2,5.0,32,60.0
5,มีนาคม,2566,100,22,33,2,4.0,47,75.0
6,เมษายน,2566,100,17,29,1,1.0,32,62.0
7,พฤษภาคม,2566,101,26,47,1,2.0,40,74.0
8,มิถุนายน,2566,101,25,39,2,3.0,34,61.0

#ขั้นที่ 1 Eyesball the Data

In [12]:
table_from_drive.describe()

,Year_,Amount_Government,Amount_Sickleave,Amount_Day_Sickleave,Amount_ Personalleave,Amount_ Day_Personalleave,Amount_ Vacationleave,Amount_ Day_Vacationleave
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,2565.666667,97.777778,20.444444,35.222222,1.666667,2.888889,38.333333,63.888889
std,0.500000,3.153481,3.244654,10.521143,1.000000,1.746027,7.000000,9.002700
min,2565.000000,94.000000,17.000000,27.000000,0.000000,0.000000,31.000000,47.000000
25%,2565.000000,95.000000,18.000000,28.000000,1.000000,2.000000,32.000000,60.000000
50%,2566.000000,100.000000,20.000000,30.000000,2.000000,3.000000,35.000000,62.000000
75%,2566.000000,100.000000,22.000000,39.000000,2.000000,4.500000,47.000000,69.500000
max,2566.000000,101.000000,26.000000,57.000000,3.000000,5.000000,47.000000,75.000000

In [13]:
table_from_drive.head() #ดูแถวบนสุด 5 แถวแรก

,Month_,Year_,Amount_Government,Amount_Sickleave,Amount_Day_Sickleave,Amount_ Personalleave,Amount_ Day_Personalleave,Amount_ Vacationleave,Amount_ Day_Vacationleave
0,ตุลาคม,2565,95,18,28,1,2.0,35,57.0
1,พฤศจิกายน,2565,95,20,57,0,0.0,31,47.0
2,ธันวาคม,2565,94,18,27,3,4.5,47,69.5
3,มกราคม,2566,94,18,27,3,4.5,47,69.5
4,กุมภาพันธ์,2566,100,20,30,2,5.0,32,60.0

In [14]:
table_from_drive.tail() #ดูแถวล่างสุด 5 แถวแรก

,Month_,Year_,Amount_Government,Amount_Sickleave,Amount_Day_Sickleave,Amount_ Personalleave,Amount_ Day_Personalleave,Amount_ Vacationleave,Amount_ Day_Vacationleave
4,กุมภาพันธ์,2566,100,20,30,2,5.0,32,60.0
5,มีนาคม,2566,100,22,33,2,4.0,47,75.0
6,เมษายน,2566,100,17,29,1,1.0,32,62.0
7,พฤษภาคม,2566,101,26,47,1,2.0,40,74.0
8,มิถุนายน,2566,101,25,39,2,3.0,34,61.0

In [15]:
table_from_drive.tail() #ดูแถวล่างสุด 7 แถวแรก

,Month_,Year_,Amount_Government,Amount_Sickleave,Amount_Day_Sickleave,Amount_ Personalleave,Amount_ Day_Personalleave,Amount_ Vacationleave,Amount_ Day_Vacationleave
4,กุมภาพันธ์,2566,100,20,30,2,5.0,32,60.0
5,มีนาคม,2566,100,22,33,2,4.0,47,75.0
6,เมษายน,2566,100,17,29,1,1.0,32,62.0
7,พฤษภาคม,2566,101,26,47,1,2.0,40,74.0
8,มิถุนายน,2566,101,25,39,2,3.0,34,61.0